---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "heap-dump-service.name" . }}-role-cm
  labels:
    app.kubernetes.io/name: {{ include "heap-dump-service.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config.json: |-
    {
        "app": {
            "port": {{ .Values.service.port }},
            "bucket": {{ .Values.heapDumpConfig.bucketName | quote }}
        },
        "vault": {
            "vaultTransitMount": {{ .Values.heapDumpConfig.vaultMount | quote }},
            "vaultRole": {{ .Values.heapDumpConfig.vaultRole | quote }},
            "vaultAuthMountPath": {{ .Values.heapDumpConfig.vaultAuthMountPath | quote }}
        },
        "serviceAccount": {
            "jwtokenMountPoint": {{ .Values.heapDumpConfig.jwtokenMountPoint | quote }}
        },
        "metrics": {
            "port": {{ .Values.heapDumpConfig.prometheus.port }},
            "path": {{ .Values.heapDumpConfig.prometheus.path | quote}}
        }
    }
