name: Build, Test, Scan

on:
  push:
    branches:
      - feature/tt/onboarding
    paths-ignore:
      - 'heap-dump-service/**'
      - 'notify-sidecar/**'

env:
  PROJECT_PATH: heap-dump-companion

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Go Test
        run: |
          cd ${{ env.PROJECT_PATH }}
          go test -v ./...

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist